### ISSUE TITLE
Treasure maps crashed the game

### ISSUE THREAD

**Issue by DerMattinger** [almic/VanillaTrees#1]
I am using the custom ocean biomes on a custom map. The shipwrecks that spawn at the bottom of the ocean with the monuments actually crash the game because they dont have a home chunk for their treasure maps.

**Comment by almic** [comment]
I'm hitting myself for not seeing this earlier. I did notice that opening treasure map chests cause huge lag because they try searching for buried treasure. On completely custom worlds with no additional world generation or structures, yeah I believe this can crash the game. I will make a default version that doesn't generate the treasure maps soon, and leave the treasure maps as an alternative for those who need it.

**Comment by almic** [comment]
Alright, should be patched up now since commit 70b5f82c1af42b88312e4ffaeb7150692b1dfec0! Took me a while but static loot is basically indistinguishable from Minecraft generated loot, and will never lag/ crash.
